version: '3.8'

services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./bkk_districts.geojson:/app/bkk_districts.geojson
      - ./map_df.pkl:/app/map_df.pkl
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0