version: '3.8'

services:
  streamlit-app:
    build: .
    volumes:
      - ./bkk_districts.geojson:/app/bkk_districts.geojson:ro
      - ./map_df.pkl:/app/map_df.pkl:ro
      - .:/app  # Keep for development; consider removing for production
    expose:
      - "8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0

  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"  # Map host port 8080 to container port 8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - streamlit-app